pub const INPUT_SMALL: [bool; 40] = [
    true, true, true, false, false, true, false, true, true, false, false, false, true, true,
    false, true, true, true, false, false, false, true, true, true, false, false, false, true,
    false, false, false, true, true, false, true, true, false, false, true, true,
];

pub const INPUT: [bool; 10091] = [
    true, false, false, false, false, true, true, true, true, false, false, false, true, false,
    false, false, true, false, false, false, true, true, false, false, true, true, true, false,
    true, true, false, true, true, false, false, false, false, true, true, false, false, false,
    false, true, true, false, false, false, true, true, true, true, false, false, false, true,
    false, false, false, true, true, true, true, false, false, false, false, true, false, false,
    true, false, false, true, true, false, false, true, true, true, true, false, false, false,
    true, true, true, false, false, false, true, true, true, true, false, false, true, true, false,
    true, true, false, false, false, false, true, true, true, false, false, false, true, true,
    true, true, false, false, false, false, true, false, false, true, true, true, false, false,
    false, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
    true, true, false, true, true, true, true, false, false, false, true, true, true, false, false,
    false, true, true, false, true, true, true, false, false, false, false, true, true, true,
    false, true, true, true, true, false, false, false, true, true, true, true, false, false,
    false, false, true, true, false, false, true, true, true, true, false, false, true, true,
    false, true, true, true, false, false, true, true, true, false, true, true, true, true, false,
    false, false, true, true, false, false, true, true, true, false, false, true, true, true,
    false, false, false, false, true, true, true, true, false, true, true, true, false, true, true,
    false, false, false, false, true, true, true, false, false, false, true, true, true, false,
    false, false, false, true, true, true, true, false, false, false, true, true, true, false,
    false, false, true, true, false, true, false, false, false, false, true, true, true, false,
    false, false, false, true, false, false, false, true, true, true, false, false, true, false,
    true, true, true, false, false, false, false, true, true, true, true, false, true, true, false,
    false, false, true, true, false, false, true, true, true, false, false, false, false, true,
    true, false, false, false, true, true, true, false, false, true, true, true, true, false, true,
    true, true, true, false, true, true, true, false, true, true, true, true, false, false, false,
    true, false, false, false, false, true, true, false, false, true, true, false, true, true,
    true, false, false, true, true, true, true, false, false, false, false, true, true, true, true,
    false, true, true, true, true, false, true, true, false, false, false, false, true, true, true,
    true, false, false, false, false, true, true, true, false, false, true, true, true, false,
    false, true, false, true, true, false, false, false, false, true, true, false, true, false,
    false, false, false, true, true, true, false, false, false, true, true, true, false, false,
    false, true, true, true, false, false, false, true, true, false, false, true, true, true, true,
    false, false, false, true, false, false, false, true, true, true, false, true, false, false,
    true, true, true, true, false, false, false, true, false, true, true, true, true, false, false,
    true, true, true, false, true, true, false, false, false, true, true, true, false, false,
    false, false, true, false, false, false, true, true, false, false, false, true, true, false,
    true, true, true, false, false, false, false, true, true, true, false, false, true, true, true,
    true, false, true, true, false, false, false, true, true, true, true, false, false, false,
    false, true, true, true, true, false, false, false, true, true, false, false, false, true,
    true, true, true, false, false, true, true, false, false, true, true, true, true, false, false,
    true, true, true, false, false, false, false, true, true, true, false, true, true, true, true,
    false, true, true, false, false, false, true, true, false, false, false, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, true, true, true, false, true, true, true, false, true, true, true, false, true,
    false, false, false, true, true, false, false, false, true, true, true, false, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true, false, false, true,
    true, true, false, false, false, false, true, true, false, true, true, false, false, true,
    true, true, true, false, true, true, false, false, true, true, false, false, false, false,
    true, true, true, false, false, false, true, true, false, false, true, false, false, false,
    false, true, true, false, false, false, false, true, true, false, false, false, false, true,
    false, false, true, true, false, true, true, true, false, false, false, true, false, false,
    false, true, false, false, false, false, true, true, false, false, false, true, true, true,
    false, false, true, true, true, false, true, true, true, false, false, false, false, true,
    true, false, false, true, false, true, true, false, false, true, true, true, false, true,
    false, false, false, false, true, true, true, true, false, false, true, true, true, true,
    false, false, false, false, true, true, true, false, true, true, false, false, false, false,
    true, true, false, false, true, true, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, true, true, false, false, true, false, false, false, false,
    true, true, true, true, false, false, false, true, false, false, false, false, true, false,
    false, false, true, true, true, true, false, false, true, true, true, false, false, true,
    false, true, true, true, true, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, false, false, false, true,
    true, false, false, true, true, true, true, false, true, true, true, true, false, true, true,
    false, false, false, true, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, false, true, true, false, false, false, true, false, false,
    false, false, true, true, true, true, false, false, true, true, false, true, true, true, false,
    false, false, true, true, true, false, true, true, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, false, false, false, true,
    true, false, false, true, true, true, false, false, false, true, true, true, false, true, true,
    true, false, true, false, true, true, true, false, false, true, true, false, false, true, true,
    true, false, false, false, false, true, true, false, false, true, false, false, false, true,
    true, false, true, false, false, true, false, false, true, true, false, true, true, true, true,
    false, false, true, true, true, true, false, false, false, false, true, true, true, false,
    true, true, true, true, false, true, true, true, false, false, false, true, true, true, false,
    false, false, true, true, true, true, false, false, true, false, true, true, true, false,
    false, false, true, true, true, false, true, true, true, true, false, true, true, true, true,
    false, true, false, false, true, true, true, true, false, false, false, true, true, true,
    false, false, false, true, true, false, false, true, true, true, true, false, true, true, true,
    true, false, false, true, false, true, true, true, true, false, false, false, true, false,
    false, false, true, true, true, true, false, false, false, false, true, true, true, true,
    false, false, true, true, true, false, false, false, false, true, true, false, false, false,
    true, true, false, true, false, false, false, true, true, true, true, false, true, true, true,
    false, true, false, true, false, false, false, true, false, false, true, true, false, false,
    true, true, true, true, false, false, false, true, false, false, true, false, false, false,
    true, true, true, true, false, false, false, false, true, true, true, false, false, true,
    false, false, true, true, true, false, false, false, true, true, true, true, false, true, true,
    true, true, false, false, false, false, true, true, false, true, true, false, false, true,
    false, false, false, true, true, false, false, false, true, true, true, false, false, false,
    false, true, true, true, true, false, false, true, false, false, false, false, true, true,
    true, true, false, true, true, false, false, false, true, true, true, true, false, false,
    false, false, true, false, false, false, false, true, true, true, true, false, false, true,
    true, false, false, true, true, false, false, true, false, false, true, true, true, true,
    false, false, true, true, true, false, false, true, false, false, true, true, true, true,
    false, false, true, true, true, true, false, false, true, true, true, true, false, false,
    false, false, true, false, false, false, false, true, false, false, false, false, true, false,
    false, false, true, true, true, false, false, false, false, true, true, true, true, false,
    true, true, true, true, false, false, false, true, true, true, false, false, true, true, true,
    false, false, false, true, true, true, true, false, true, true, true, false, false, true, true,
    true, true, false, false, false, true, true, false, false, true, true, true, false, false,
    true, false, true, true, false, false, false, true, true, false, false, true, false, false,
    true, true, true, true, false, false, true, true, false, false, false, false, true, true,
    false, false, false, true, true, true, true, false, false, false, true, true, true, false,
    false, true, true, true, false, false, true, true, true, false, false, true, true, true, true,
    false, false, false, false, true, true, false, true, true, true, false, true, true, true,
    false, true, false, false, false, true, false, true, true, true, false, false, false, true,
    true, true, false, true, false, false, true, true, true, true, false, false, true, false,
    false, false, false, true, true, false, false, false, false, true, true, true, false, false,
    false, false, true, true, true, false, false, false, false, true, true, true, false, false,
    false, true, true, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, false, false, true, true, true, false, false, false, false,
    true, true, false, true, true, true, true, false, true, true, true, false, true, true, false,
    false, false, true, false, false, false, true, false, false, true, true, false, false, true,
    false, false, false, false, true, false, false, false, false, true, true, false, false, false,
    false, true, false, true, true, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, true, true, true, false, false, false, true, true,
    true, false, true, true, true, false, false, true, true, false, false, true, false, false,
    true, true, true, true, false, false, true, true, false, false, false, false, true, true, true,
    false, false, false, true, true, true, true, false, false, true, true, true, false, false,
    true, true, false, false, false, true, false, false, false, false, true, true, true, true,
    false, false, true, true, false, true, true, true, true, false, false, false, false, true,
    false, true, true, true, false, false, true, true, true, false, true, true, true, false, false,
    false, true, true, true, false, true, true, false, false, true, true, false, false, true, true,
    true, true, false, false, false, false, true, false, false, true, true, false, false, false,
    false, true, true, true, true, false, false, false, false, true, true, true, false, false,
    false, false, true, false, true, true, true, true, false, true, true, true, false, false, true,
    false, true, true, true, false, false, false, false, true, true, true, true, false, true, true,
    false, false, false, true, false, true, false, true, true, false, true, false, true, false,
    false, false, false, true, true, false, false, false, false, true, true, true, false, false,
    false, true, false, false, false, false, true, true, false, true, true, true, true, false,
    false, false, true, false, false, false, false, true, true, true, false, false, true, true,
    true, false, true, true, true, false, false, false, true, true, true, false, false, false,
    false, true, true, false, true, false, false, false, true, true, true, false, false, true,
    true, true, true, false, true, false, false, false, false, true, false, false, true, false,
    false, true, false, false, false, true, true, true, false, true, true, false, true, true, true,
    false, false, false, true, true, false, false, false, false, true, true, true, true, false,
    false, false, true, true, false, false, false, false, true, false, false, false, false, true,
    true, true, false, false, false, false, true, false, false, true, true, true, true, false,
    false, false, true, true, false, true, true, false, false, false, true, true, true, false,
    false, false, false, true, true, false, true, true, true, false, false, false, false, true,
    true, false, false, false, false, true, true, true, false, false, false, false, true, true,
    true, true, false, false, true, true, false, false, false, true, true, false, false, true,
    true, true, false, false, true, true, true, true, false, true, true, false, false, true, false,
    false, false, true, true, true, false, false, false, false, true, false, false, true, true,
    false, false, false, false, true, true, true, false, false, false, true, true, true, true,
    false, false, true, true, false, false, true, false, true, true, false, false, false, true,
    true, true, false, true, true, false, false, false, false, true, true, true, false, false,
    false, false, true, false, false, true, true, false, false, false, true, true, true, false,
    false, true, true, true, true, false, false, false, true, true, true, true, false, false,
    false, false, true, true, false, false, false, false, true, false, false, false, false, true,
    true, true, true, false, false, false, false, true, true, true, true, false, false, true,
    false, false, false, false, true, true, true, true, false, true, true, true, true, false,
    false, false, false, true, true, true, false, false, false, false, true, true, false, false,
    true, true, false, false, false, false, true, true, true, false, false, false, false, true,
    true, true, true, false, false, true, true, false, false, true, true, false, false, false,
    false, true, false, false, false, false, true, true, true, false, false, false, true, false,
    false, false, true, true, false, true, true, true, true, false, true, true, true, true, false,
    false, true, true, false, false, false, false, true, true, true, true, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true, true, true,
    false, false, false, false, true, false, false, false, true, true, true, true, false, false,
    true, true, true, true, false, false, true, false, false, false, false, true, true, false,
    true, false, false, false, true, true, true, false, false, false, true, false, true, true,
    false, false, false, false, true, false, false, false, true, true, true, true, false, true,
    true, false, false, true, true, true, false, false, false, true, true, true, true, false,
    false, true, true, true, false, false, false, true, true, false, false, true, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, false, true, true,
    true, false, false, true, true, true, true, false, false, false, false, true, true, true,
    false, false, false, false, true, true, false, false, true, true, true, false, false, false,
    true, false, true, true, true, false, false, true, true, true, false, true, true, false, false,
    true, false, true, true, true, false, false, false, true, false, false, true, true, true,
    false, false, false, true, true, true, false, false, false, true, true, false, false, true,
    true, true, false, true, true, false, true, true, false, true, false, false, false, false,
    true, true, true, false, false, false, true, true, false, false, false, false, true, true,
    true, true, false, false, false, false, true, true, false, true, true, true, false, false,
    false, false, true, false, true, true, true, false, true, false, false, false, false, true,
    true, true, false, false, false, true, true, true, true, false, true, true, true, false, false,
    false, true, true, false, true, true, false, false, false, true, true, true, true, false,
    false, false, false, true, false, false, false, true, true, true, false, false, true, false,
    false, true, true, true, false, false, false, true, true, true, true, false, true, false,
    false, false, true, true, true, false, false, true, true, false, false, false, true, false,
    false, false, false, true, true, false, true, true, true, false, false, true, false, false,
    true, true, true, false, false, false, false, true, true, false, false, false, false, true,
    true, false, false, false, false, true, false, false, true, false, true, true, true, false,
    true, false, false, true, true, true, true, false, false, true, true, true, true, false, false,
    false, false, true, true, true, false, false, false, true, true, false, false, false, true,
    false, false, false, false, true, true, true, true, false, false, true, true, true, false,
    false, false, true, true, true, false, true, true, true, false, false, false, true, false,
    true, true, true, true, false, false, false, true, false, false, false, false, true, true,
    true, true, false, true, true, false, true, true, false, false, false, true, true, true, true,
    false, false, false, true, true, false, false, true, true, false, false, true, true, true,
    false, false, false, false, true, true, false, false, false, false, true, true, true, true,
    false, false, false, false, true, true, true, true, false, false, true, false, true, true,
    true, true, false, false, false, false, true, true, true, true, false, false, false, false,
    true, true, false, false, false, false, true, false, false, false, false, true, true, true,
    false, false, false, false, true, true, false, false, false, true, true, true, true, false,
    true, true, false, false, false, true, false, false, false, false, true, true, true, false,
    false, true, true, true, true, false, false, false, true, true, false, false, false, true,
    true, true, false, true, true, true, false, false, false, true, false, true, false, false,
    true, false, false, true, true, true, false, true, true, true, false, false, false, true, true,
    false, false, false, true, true, true, true, false, false, false, false, true, true, true,
    true, false, false, false, false, true, true, false, false, false, true, true, true, false,
    false, false, true, true, false, false, true, true, false, true, true, true, true, false,
    false, false, false, true, true, false, false, false, true, true, true, true, false, false,
    false, true, true, false, false, false, true, true, true, true, false, true, true, true, true,
    false, true, true, true, false, false, false, false, true, false, true, true, true, false,
    true, true, true, false, false, true, true, false, true, false, false, false, true, true, true,
    true, false, false, false, false, true, true, true, true, false, false, true, true, false,
    false, true, true, true, false, true, false, true, true, false, false, false, false, true,
    true, false, false, false, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, false, false, false, true, true, true, false, false, true, true,
    true, false, false, false, true, true, true, true, false, false, true, false, false, false,
    false, true, true, false, true, true, true, false, false, false, true, true, true, false,
    false, true, false, false, false, false, true, true, false, false, false, false, true, true,
    true, false, false, false, false, true, true, true, true, false, false, false, true, false,
    false, false, false, true, true, true, false, false, false, false, true, true, true, true,
    false, false, false, true, true, true, false, true, false, false, true, true, true, true,
    false, true, true, true, true, false, false, false, false, true, true, true, false, false,
    false, true, true, true, false, false, false, false, true, false, false, false, true, true,
    false, false, false, true, false, false, false, true, true, false, false, false, true, true,
    true, true, false, false, false, false, true, true, true, true, false, false, true, true, true,
    false, false, true, true, false, false, true, true, true, true, false, false, false, true,
    true, false, true, false, false, false, true, true, true, true, false, true, false, false,
    false, true, true, true, true, false, false, true, false, false, true, true, true, false, true,
    true, true, false, false, false, false, true, true, false, false, false, false, true, true,
    true, true, false, false, false, false, true, false, false, false, true, true, true, true,
    false, false, true, true, false, false, false, true, true, false, false, false, true, true,
    false, false, false, false, true, true, false, true, true, true, true, false, false, false,
    false, true, false, false, false, false, true, true, true, true, false, true, false, false,
    true, true, false, false, true, true, false, false, false, false, true, true, false, false,
    false, false, true, true, true, true, false, false, false, false, true, true, true, false,
    false, true, false, false, true, false, false, true, true, true, true, false, true, true, true,
    true, false, false, true, false, false, false, true, true, true, false, false, true, true,
    true, false, false, true, true, false, true, true, false, false, false, true, false, false,
    true, true, true, true, false, false, false, true, true, true, false, true, true, true, true,
    false, true, true, true, false, false, true, false, false, true, false, false, true, false,
    true, true, false, true, true, true, true, false, true, true, false, true, true, false, false,
    true, true, false, false, false, true, true, false, false, true, true, false, false, false,
    false, true, true, true, false, false, false, false, true, true, true, false, true, false,
    false, false, true, true, true, true, false, true, false, false, true, true, false, true, true,
    true, false, true, true, false, false, false, true, false, false, true, true, false, false,
    true, false, true, false, false, false, true, true, true, true, false, false, false, false,
    true, true, true, true, false, false, false, false, true, false, true, true, true, true, false,
    false, false, false, true, true, true, false, false, true, true, true, true, false, false,
    false, true, true, false, false, false, false, true, true, false, false, true, true, true,
    true, false, false, false, false, true, true, true, true, false, false, true, true, true,
    false, false, false, false, true, true, false, false, false, true, true, true, false, false,
    false, false, true, true, false, false, true, true, false, false, false, true, true, true,
    true, false, true, true, true, true, false, false, false, false, true, false, false, false,
    false, true, true, true, false, false, false, false, true, true, false, false, false, false,
    true, true, true, true, false, false, false, true, true, false, false, false, false, true,
    true, true, false, true, true, false, true, false, false, false, false, true, false, false,
    true, false, false, false, true, true, false, false, true, false, false, false, true, true,
    true, false, false, false, true, true, true, false, false, true, false, false, true, true,
    true, false, false, true, true, true, true, false, false, false, false, true, true, false,
    true, true, true, true, false, false, true, false, false, true, true, true, false, false, true,
    true, true, true, false, false, true, false, false, false, false, true, true, false, true,
    true, false, true, true, false, false, true, true, false, false, false, true, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, true, false, false,
    false, false, true, true, true, true, false, false, false, false, true, true, true, true,
    false, false, true, true, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, true, true, true, false, false, false, true, false, false, false,
    true, true, true, true, false, false, true, true, true, false, false, false, false, true, true,
    true, true, false, false, false, false, true, false, false, true, true, false, false, true,
    true, true, false, false, true, true, false, false, false, true, true, true, true, false, true,
    true, false, true, true, false, false, false, true, false, false, false, true, true, true,
    false, false, false, true, false, true, true, true, true, false, true, true, true, false, true,
    false, false, false, false, true, true, false, false, false, true, true, true, true, false,
    false, false, false, true, true, false, false, true, true, false, false, false, true, true,
    true, true, false, true, true, true, true, false, false, true, true, true, false, false, false,
    false, true, true, true, false, false, false, true, true, true, true, false, false, false,
    false, true, true, false, false, false, false, true, true, true, true, false, false, false,
    false, true, true, false, false, false, true, false, false, true, true, true, false, false,
    true, true, true, false, true, false, false, false, true, false, false, false, true, true,
    false, false, true, true, true, true, false, true, true, false, false, false, true, true,
    false, false, true, true, false, false, false, false, true, true, true, false, false, true,
    false, false, false, true, true, true, false, false, true, true, true, true, false, false,
    false, false, true, false, false, true, true, true, true, false, true, false, true, true, true,
    true, false, false, true, true, true, false, false, false, false, true, false, false, false,
    false, true, true, false, false, false, true, false, false, false, true, false, false, true,
    false, false, false, true, true, true, false, false, false, false, true, false, false, false,
    true, true, false, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, true, false, false, false,
    true, true, true, false, false, false, true, false, false, true, false, true, false, false,
    true, true, true, true, false, true, true, true, false, false, false, false, true, true, true,
    true, false, false, false, false, true, true, true, false, false, true, true, true, false,
    false, false, false, true, false, false, false, false, true, true, true, false, false, false,
    true, false, false, false, false, true, true, false, false, true, false, false, true, false,
    false, false, true, true, false, false, true, true, false, false, true, true, true, false,
    false, true, true, true, false, false, true, true, true, false, true, true, true, false, false,
    false, true, true, true, true, false, false, false, false, true, true, true, false, true, true,
    true, false, false, false, true, true, false, false, true, false, false, true, true, true,
    true, false, false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, false, false, true, false, false, true,
    false, false, false, true, false, false, false, true, false, true, true, true, true, false,
    true, false, false, false, false, true, false, false, false, true, true, true, true, false,
    true, true, true, false, true, true, true, true, false, true, true, false, false, true, true,
    false, false, false, false, true, true, true, true, false, false, true, true, true, false,
    true, true, false, true, true, false, true, true, true, false, false, false, false, true, true,
    true, false, true, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, false, false, true, true, false, true, true, true, true, false, true, true,
    true, false, false, true, true, true, true, false, false, false, true, true, true, true, false,
    false, true, true, false, false, false, false, true, false, false, false, true, true, false,
    true, false, false, false, false, true, true, true, true, false, true, true, true, true, false,
    true, true, true, false, false, false, true, true, true, true, false, true, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, true, false, false, true, false, false, true, true, true, false, false,
    true, false, false, true, true, false, true, true, true, true, false, false, false, true, true,
    true, false, false, false, true, true, true, false, false, false, true, true, true, false,
    true, false, false, false, false, true, true, true, false, true, true, false, false, false,
    false, true, false, false, true, true, true, false, false, true, true, false, false, false,
    false, true, false, false, false, false, true, true, false, false, true, true, false, false,
    true, true, false, false, true, true, true, true, false, false, false, true, true, true, true,
    false, true, true, true, false, false, false, true, true, true, true, false, false, false,
    true, true, false, false, false, false, true, true, true, false, true, true, false, false,
    true, true, true, false, true, false, false, true, true, true, false, false, false, true, true,
    true, false, true, true, false, false, true, true, false, false, false, false, true, true,
    false, false, false, true, true, true, true, false, false, false, false, true, true, false,
    false, true, true, false, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, false, true, false, false, false, false, true,
    true, false, false, false, false, true, true, false, false, false, false, true, true, true,
    true, false, false, true, true, false, false, false, false, true, true, true, true, false,
    false, false, false, true, true, true, true, false, true, true, true, true, false, true, true,
    true, false, true, true, true, false, false, false, false, true, false, false, false, true,
    true, false, false, true, true, true, true, false, true, false, false, true, true, true, false,
    true, true, true, true, false, false, false, false, true, true, true, true, false, true, true,
    false, true, true, true, true, false, true, true, true, true, false, false, false, true, false,
    false, false, true, true, true, false, false, true, true, true, true, false, false, false,
    false, true, false, true, true, true, false, false, true, true, false, false, false, true,
    true, true, true, false, false, true, true, true, true, false, false, true, true, false, false,
    false, true, false, false, false, true, true, true, false, false, false, true, false, false,
    true, false, false, true, true, true, false, true, true, false, true, true, true, false, false,
    true, true, true, true, false, false, false, true, true, false, false, true, true, true, false,
    false, false, true, true, true, true, false, false, true, true, false, true, false, false,
    true, true, false, false, false, false, true, true, true, false, false, false, true, true,
    false, false, false, true, true, true, false, true, true, false, false, true, true, true,
    false, false, false, false, true, true, true, true, false, false, true, true, false, false,
    true, true, false, false, false, false, true, true, true, true, false, false, true, true, true,
    false, true, true, true, true, false, true, true, false, false, true, true, false, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false, false, true, true,
    true, false, false, true, true, true, true, false, false, true, false, false, true, false,
    false, false, true, false, false, true, true, true, true, false, false, true, true, true, true,
    false, false, true, false, true, true, true, false, false, true, false, false, false, true,
    true, true, true, false, true, false, false, true, true, false, false, false, true, true,
    false, false, false, true, true, true, true, false, false, true, true, false, false, false,
    false, true, true, true, true, false, true, true, false, false, false, true, true, false, true,
    true, true, false, false, false, true, true, true, false, false, false, true, true, true, true,
    false, false, false, false, true, true, true, false, false, false, true, true, false, false,
    false, false, true, true, true, false, true, false, false, false, false, true, true, true,
    true, false, false, true, false, false, true, true, false, false, false, false, true, false,
    false, true, false, false, true, true, true, true, false, true, true, false, true, true, false,
    true, true, true, false, false, false, true, true, true, true, false, false, false, false,
    true, false, false, false, true, true, false, false, true, true, true, true, false, true,
    false, false, false, true, false, false, true, true, true, false, false, false, false, true,
    false, false, false, false, true, true, true, true, false, false, false, true, true, true,
    true, false, false, false, true, true, false, false, false, true, true, false, false, false,
    true, false, false, true, false, false, true, false, true, false, false, false, false, true,
    true, true, true, false, false, false, false, true, false, false, false, true, true, false,
    false, false, false, true, false, false, false, false, true, false, false, false, false, true,
    true, true, true, false, false, false, true, true, false, false, false, true, true, true, true,
    false, false, false, false, true, true, false, true, true, false, false, true, true, false,
    true, true, true, true, false, true, true, false, false, true, true, false, false, true, false,
    false, false, true, false, false, false, true, true, false, false, false, true, true, true,
    false, false, false, false, true, true, true, false, false, false, true, true, true, true,
    false, true, true, true, false, false, false, true, false, true, false, false, false, false,
    true, true, true, false, false, false, false, true, true, false, false, false, false, true,
    true, true, true, false, true, true, true, false, false, false, false, true, true, true, true,
    false, false, true, true, true, true, false, false, false, false, true, false, false, true,
    true, true, true, false, false, false, false, true, false, false, true, true, true, false,
    false, false, true, true, true, false, false, false, true, false, false, false, false, true,
    true, true, true, false, false, false, false, true, true, false, false, false, false, true,
    true, false, false, false, false, true, false, false, false, true, true, true, false, false,
    false, false, true, false, false, false, false, true, true, false, false, false, true, true,
    false, false, false, false, true, true, false, false, true, true, true, true, false, true,
    false, false, true, true, true, false, true, true, true, false, false, false, true, true,
    false, false, true, false, false, true, false, false, true, true, false, false, true, false,
    true, false, false, true, true, true, true, false, true, false, true, true, true, false, false,
    false, true, true, false, true, true, true, false, false, false, true, true, true, false,
    false, false, true, true, false, false, false, false, true, true, true, false, false, true,
    true, true, false, false, true, true, true, true, false, false, true, true, true, false, false,
    false, false, true, true, false, false, false, false, true, false, true, true, true, true,
    false, true, true, true, true, false, false, false, false, true, true, true, false, false,
    false, true, true, false, true, false, true, false, false, true, true, true, true, false,
    false, true, false, false, false, true, true, true, true, false, false, true, true, false,
    false, false, true, false, true, false, false, false, false, true, false, false, false, true,
    false, false, false, true, true, false, false, false, false, true, true, true, false, false,
    false, false, true, true, false, false, false, false, true, true, false, false, false, false,
    true, true, true, true, false, false, false, false, true, true, true, true, false, true, false,
    true, true, true, true, false, false, true, true, true, false, false, true, false, false,
    false, true, true, true, false, false, false, true, false, true, true, true, true, false,
    false, false, false, true, true, true, true, false, true, true, false, false, false, true,
    true, false, false, true, true, false, false, true, true, true, true, false, false, false,
    false, true, false, true, true, true, false, false, false, false, true, true, false, false,
    true, false, false, true, true, false, false, false, false, true, true, true, false, true,
    false, false, false, true, false, false, false, true, false, false, false, true, true, true,
    false, false, true, true, false, false, false, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, false, true, false, true, true, true, true,
    false, true, false, true, true, false, false, false, true, true, true, false, false, false,
    false, true, true, true, true, false, false, false, true, true, true, true, false, false, true,
    true, false, false, true, false, false, true, true, false, false, false, false, true, true,
    true, false, false, false, false, true, true, false, false, true, true, true, true, false,
    false, true, true, false, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, false, false, false, true, true, true, false, false, true, true,
    false, false, false, false, true, false, true, false, false, true, true, false, true, true,
    true, false, false, true, false, false, false, true, true, false, false, false, true, true,
    false, false, false, true, true, true, true, false, false, true, true, false, false, false,
    false, true, true, true, false, false, false, true, true, true, true, false, true, true, true,
    false, false, false, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, false, false, false, true, true, false, false, false, true,
    true, true, false, true, false, false, false, false, true, true, true, false, false, true,
    true, true, true, false, false, false, true, true, true, false, true, true, false, true, false,
    true, true, false, false, false, true, false, false, false, false, true, false, false, false,
    false, true, true, true, true, false, false, false, true, true, true, false, true, false,
    false, false, true, false, false, false, true, true, false, false, true, true, false, false,
    true, false, false, true, false, true, true, false, true, false, false, false, true, true,
    false, false, false, false, true, true, false, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, true, false, false, false, false, true, false,
    false, false, true, true, true, true, false, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, false, true, true, true, true, false, false,
    false, true, true, false, false, false, false, true, true, true, false, false, false, false,
    true, true, false, false, true, true, false, true, false, false, false, false, true, true,
    false, false, true, true, true, false, false, false, false, true, true, false, false, false,
    true, true, true, true, false, false, true, false, true, true, true, true, false, false, false,
    false, true, true, true, true, false, true, false, true, true, true, false, false, true, true,
    true, true, false, true, true, false, false, true, true, true, true, false, true, false, true,
    true, false, false, true, true, true, false, true, false, true, true, true, false, false,
    false, true, true, true, true, false, false, false, false, true, true, true, false, false,
    false, true, false, false, false, false, true, true, true, true, false, false, false, true,
    true, false, false, false, false, true, true, false, false, false, true, true, false, true,
    true, false, false, false, true, true, true, false, false, false, false, true, true, false,
    false, true, true, true, false, true, true, false, false, false, false, true, true, true, true,
    false, false, false, true, true, false, false, true, true, false, true, true, true, false,
    false, false, false, true, true, true, true, false, true, false, false, true, false, false,
    false, true, true, true, false, false, false, false, true, true, false, false, false, false,
    true, true, false, true, false, true, true, true, false, false, true, true, false, true, true,
    true, true, false, false, false, false, true, true, true, true, false, false, false, true,
    true, true, false, false, false, true, true, false, false, false, false, true, true, true,
    true, false, false, false, true, true, false, false, true, true, true, false, false, false,
    true, true, true, false, true, true, true, false, false, false, true, false, false, false,
    false, true, true, true, true, false, false, true, false, false, false, false, true, false,
    false, false, true, true, true, true, false, true, true, true, true, false, false, false, true,
    true, false, true, true, true, true, false, true, false, false, false, false, true, true,
    false, false, false, false, true, true, true, true, false, false, false, true, true, true,
    false, true, true, true, true, false, true, true, false, false, false, true, true, true, true,
    false, false, true, false, false, false, true, true, true, false, false, true, false, false,
    false, true, true, true, true, false, false, true, true, false, false, true, true, true, false,
    false, false, true, true, true, true, false, false, false, false, true, true, false, true,
    true, true, false, false, false, false, true, false, false, false, false, true, true, true,
    true, false, true, true, false, false, false, true, true, true, false, false, true, false,
    true, true, false, false, false, true, true, false, true, true, true, false, false, false,
    true, true, true, false, false, false, false, true, true, true, true, false, false, false,
    true, true, true, true, false, true, true, true, false, false, true, false, false, false,
    false, true, true, true, true, false, true, false, false, false, true, true, true, true, false,
    false, true, true, true, false, true, false, false, false, true, true, true, false, false,
    false, false, true, true, false, false, false, true, true, true, false, false, true, true,
    true, false, false, false, true, false, false, true, false, false, false, true, true, false,
    false, true, true, false, false, false, false, true, true, true, false, false, false, true,
    false, true, false, true, true, false, false, true, true, true, false, false, false, false,
    true, true, true, false, true, true, true, true, false, false, true, false, false, false,
    false, true, true, true, true, false, false, false, false, true, false, false, false, true,
    true, true, false, false, false, true, true, false, false, true, true, true, true, false, true,
    true, true, true, false, false, false, true, false, false, true, true, true, false, false,
    false, true, true, true, true, false, false, true, false, false, false, true, true, true,
    false, true, false, false, false, false, true, true, false, false, false, false, true, false,
    false, false, false, true, true, false, false, true, true, false, false, false, false, true,
    true, true, true, false, false, false, true, true, false, false, false, false, true, false,
    false, false, false, true, true, true, false, false, true, true, true, false, false, false,
    true, true, true, false, false, false, false, true, false, false, false, false, true, true,
    true, false, false, false, false, true, true, true, true, false, false, false, true, true,
    true, false, false, true, false, false, false, false, true, true, true, false, false, false,
    false, true, true, true, false, true, false, false, false, true, true, true, false, false,
    true, false, false, false, true, true, false, true, true, true, false, false, false, false,
    true, true, true, true, false, false, false, false, true, true, true, false, false, true, true,
    false, false, false, false, true, true, false, false, false, true, false, false, false, false,
    true, false, false, true, true, true, true, false, false, false, false, true, true, true, true,
    false, false, true, true, true, true, false, false, false, false, true, true, true, false,
    false, false, true, true, true, true, false, false, true, true, true, false, false, true, true,
    true, false, false, false, false, true, false, false, false, false, true, true, true, true,
    false, true, false, false, false, true, true, true, false, false, false, true, true, true,
    false, true, false, false, false, false, true, true, true, false, false, true, true, true,
    true, false, false, false, false, true, true, true, false, false, false, true, true, false,
    false, true, true, true, true, false, false, false, false, true, true, false, false, true,
    true, false, false, false, false, true, true, false, false, false, false, true, true, true,
    true, false, false, false, true, false, true, true, true, true, false, false, false, true,
    false, false, false, false, true, true, false, true, true, true, false, true, true, false,
    false, false, false, true, true, true, false, true, true, true, true, false, true, true, false,
    true, true, false, false, false, false, true, true, true, true, false, false, false, false,
    true, false, true, true, true, false, false, false, false, true, true, false, true, true,
    false, true, false, true, false, false, true, true, false, false, false, true, true, false,
    false, false, true, false, true, true, true, false, false, false, false, true, false, false,
    false, true, true, false, false, false, false, true, true, false, false, false, false, true,
    true, true, false, false, true, true, true, true, false, false, true, false, false, false,
    false, true, true, false, false, false, true, true, true, false, false, false, true, true,
    false, true, true, false, true, true, true, true, false, false, false, false, true, true, true,
    false, false, true, true, false, false, true, true, false, false, true, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, false, true, false,
    false, true, true, false, true, true, false, true, true, true, true, false, false, false, true,
    true, true, false, false, false, false, true, true, false, false, true, true, true, true,
    false, false, true, true, true, false, true, true, true, true, false, false, true, true, true,
    true, false, false, false, false, true, true, true, true, false, false, false, false, true,
    true, true, false, false, true, true, false, false, false, true, true, true, false, false,
    true, true, true, true, false, false, true, true, true, true, false, false, false, true, false,
    false, false, true, true, true, true, false, false, false, false, true, true, true, true,
    false, false, false, true, false, false, true, false, false, true, true, true, true, false,
    true, true, true, false, false, true, true, false, false, true, true, false, false, false,
    true, true, true, true, false, false, false, true, false, false, true, true, true, false,
    false, true, false, false, false, true, true, true, true, false, false, false, true, true,
    true, false, true, true, true, false, false, false, true, true, false, false, false, true,
    true, false, true, true, true, false, false, false, false, true, true, false, false, false,
    true, true, true, true, false, false, true, false, false, true, true, true, false, true, true,
    true, false, true, true, false, false, true, true, false, false, false, true, true, true, true,
    false, false, true, true, false, false, false, false, true, false, true, false, false, false,
    true, false, false, true, true, true, true, false, false, true, true, false, false, false,
    true, true, true, true, false, false, false, true, false, false, false, false, true, false,
    false, true, false, false, false, false, true, true, true, true, false, false, false, false,
    true, true, false, false, true, false, true, true, true, false, false, false, true, false,
    true, false, false, false, false, true, true, false, false, true, true, false, false, false,
    false, true, false, true, true, false, false, true, false, false, false, true, true, false,
    false, false, true, true, true, true, false, true, true, false, true, true, true, false, false,
    false, true, false, true, false, false, false, true, true, false, false, false, true, true,
    false, true, true, true, false, true, true, false, false, false, false, true, true, false,
    false, false, true, true, true, false, false, false, true, true, true, true, false, true, true,
    false, true, true, true, true, false, false, true, true, false, false, false, true, true, true,
    false, false, true, true, true, false, false, true, false, false, true, true, false, false,
    true, true, false, true, false, false, false, true, true, true, false, false, false, true,
    true, false, false, false, false, true, true, false, false, false, true, true, true, false,
    false, false, false, true, true, false, false, false, true, true, true, false, false, false,
    true, true, true, false, false, false, false, true, false, false, false, false, true, true,
    true, false, true, true, false, false, false, false, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, false, false, true, true, true, false,
    false, true, true, true, false, true, true, true, false, false, true, false, false, false,
    true, false, false, false, false, true, false, false, true, true, true, true, false, false,
    false, true, false, false, true, true, true, false, true, true, true, true, false, false,
    false, true, true, true, true, false, true, true, true, true, false, false, true, false, false,
    false, true, true, true, false, true, true, true, false, false, true, true, true, false, false,
    true, true, true, true, false, true, true, true, true, false, true, true, true, false, false,
    true, true, false, false, false, true, true, true, false, false, false, true, true, false,
    true, true, false, true, true, true, true, false, false, false, true, false, true, true, true,
    false, true, true, false, true, true, true, false, true, true, true, false, false, false, true,
    true, true, true, false, false, true, true, true, true, false, false, false, true, true, true,
    false, false, false, false, true, true, false, true, true, false, true, false, false, true,
    true, true, true, false, true, true, false, false, true, false, false, false, false, true,
    false, true, false, true, false, false, true, true, true, true, false, false, false, false,
    true, true, true, false, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, false, true, true, true, false, false, false, true, true,
    false, false, false, true, true, true, false, false, false, false, true, true, false, false,
    true, true, false, false, false, false, true, true, true, false, false, false, true, true,
    false, false, false, false, true, true, true, false, false, false, false, true, true, false,
    true, true, false, true, true, true, true, false, true, true, true, false, true, true, false,
    false, false, false, true, true, false, false, false, false, true, false, true, true, true,
    false, true, true, false, true, true, true, false, false, false, false, true, true, true, true,
    false, false, false, true, false, false, true, true, true, false, false, true, true, true,
    true, false, false, false, false, true, true, false, false, false, false, true, false, true,
    true, false, true, true, false, false, true, true, true, false, false, true, true, false,
    false, true, false, true, true, false, true, false, false, true, true, true, true, false,
    false, false, false, true, true, true, true, false, false, false, false, true, true, true,
    true, false, false, true, true, true, false, false, false, false, true, false, true, true,
    true, true, false, false, false, false, true, true, true, false, false, false, true, true,
    false, false, true, true, true, true, false, true, true, true, false, false, false, true, true,
    true, false, false, true, true, true, true, false, false, false, true, true, false, false,
    false, true, false, false, false, false, true, true, true, true, false, false, false, true,
    true, true, true, false, false, false, false, true, true, false, false, false, true, false,
    false, false, false, true, true, true, true, false, true, false, true, false, true, false,
    true, true, true, false, false, false, true, true, false, false, false, true, true, false,
    false, false, true, true, true, false, false, true, true, false, false, false, false, true,
    true, false, false, false, false, true, true, true, false, false, false, true, true, false,
    false, false, false, true, true, false, true, true, false, false, false, true, true, false,
    false, false, true, true, true, true, false, false, false, true, true, true, true, false,
    false, true, true, false, false, false, false, true, true, true, false, false, true, true,
    true, true, false, false, true, true, false, false, true, true, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, true, true, false, false,
    true, true, true, true, false, false, false, true, true, true, true, false, false, true, false,
    false, false, false, true, false, false, true, true, false, false, false, true, true, false,
    false, false, true, true, false, false, true, false, false, false, true, true, false, true,
    false, true, true, true, false, false, true, true, true, false, false, true, false, true, true,
    true, false, false, false, false, true, true, true, true, false, false, false, true, true,
    true, false, false, true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, true, true, true, false, false, false, false, true, true, false, false,
    false, false, true, true, false, false, true, true, false, true, true, true, false, false,
    true, true, false, false, true, false, false, false, true, true, true, false, false, false,
    true, true, false, false, true, false, false, true, true, false, false, true, false, false,
    false, false, true, true, true, false, true, true, true, false, false, true, false, false,
    false, true, true, true, true, false, false, true, true, true, true, false, true, true, true,
    false, false, true, true, true, false, false, true, false, true, false, false, false, false,
    true, true, true, false, false, true, false, false, false, true, true, false, false, false,
    true, false, false, true, true, true, false, false, false, false, true, true, true, true,
    false, false, true, true, true, true, false, true, false, true, true, true, false, false,
    false, true, true, true, true, false, false, false, true, true, false, false, false, false,
    true, false, false, false, false, true, false, false, false, false, true, true, true, false,
    true, false, false, false, true, true, false, false, false, false, true, true, true, false,
    false, false, false, true, false, false, false, true, true, true, false, false, false, true,
    true, false, false, false, false, true, true, false, false, false, false, true, true, true,
    true, false, false, false, false, true, false, true, true, false, false, false, true, true,
    true, false, false, false, false, true, false, false, true, false, false, false, false, true,
    false, false, false, false, true, true, true, false, false, true, true, true, false, true,
    true, true, true, false, false, false, true, true, true, false, true, true, true, false, false,
    true, true, false, true, true, false, false, false, false, true, false, false, false, false,
    true, true, true, true, false, false, false, true, true, true, false, false, false, true,
    false, false, true, true, true, true, false, false, true, false, false, false, false, true,
    true, false, false, true, true, true, true, false, false, false, true, true, false, false,
    false, false, true, false, false, false, false, true, true, true, false, true, true, false,
    true, false, false, false, true, true, true, true, false, false, false, false, true, true,
    false, true, true, true, true, false, true, true, true, false, false, false, false, true, true,
    true, true, false, false, true, true, false, false, true, true, false, true, true, true, false,
    false, true, false, false, true, false, true, true, true, true, false, false, false, false,
    true, true, true, false, false, false, true, true, false, true, true, true, false, false,
    false, true, false, true, true, true, false, false, false, false, true, true, false, false,
    false, false, true, true, true, true, false, true, true, true, false, true, true, true, false,
    true, true, true, true, false, true, true, false, false, true, true, true, false, false, false,
    false, true, true, false, true, true, true, false, false, true, false, false, false, true,
    true, true, false, false, true, true, true, true, false, true, true, true, true, false, false,
    true, true, true, false, false, false, false, true, true, true, false, false, true, false,
    false, false, true, false, false, false, true, false, false, false, false, true, true, true,
    true, false, false, false, true, true, true, true, false, false, false, true, true, true,
    false, false, false, false, true, true, true, true, false, false, false, false, true, true,
    true, true, false, false, true, true, false, false, false, false, true, true, true, false,
    false, true, true, true, false, true, false, false, true, true, false, false, true, false,
    true, true, true, false, false, true, true, true, false, true, true, true, true, false, false,
    false, true, true, true, true, false, false, false, false, true, true, true, false, false,
    false, true, false, false, false, false, true, false, true, true, true, false, false, true,
    false, true, true, true, true, false, false, false, false, true, true, true, true, false,
    false, false, true, true, true, false, true, true, true, true, false, false, false, false,
    true, true, true, false, false, false, true, true, true, true, false, false, true, true, true,
    false, false, false, true, false, false, true, true, true, true, false, false, true, true,
    true, true, false, false, false, false, true, false, true, true, true, true, false, false,
    true, true, true, false, false, false, false, true, false, false, false, true, false, true,
    true, true, true, false, false, false, false, true, true, true, false, false, false, true,
    true, false, true, true, false, false, true, true, false, true, true, true, false, true, true,
    true, false, false, false, true, true, false, false, true, false, true, true, false, false,
    false, false, true, true, false, false, false, false, true, false, false, false, false, true,
    true, true, false, false, false, true, true, true, true, false, false, false, false, true,
    true, true, true, false, true, true, true, true, false, false, false, false, true, true, false,
    false, false, false, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, true, true, false, false, false, true, true, true, true, false, true, true,
    true, false, false, true, true, true, true, false, false, false, true, true, false, true, true,
    true, true, false, false, false, false, true, true, true, true, false, false, false, true,
    true, false, false, true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, true, false, false, true, true, true, true, false, false, false, false, true,
    true, true, true, false, false, false, false, true, true, false, false, false, false, true,
    true, true, true, false, true, true, true, false, false, true, true, true, false, false, false,
    true, true, true, true, false, false, false, true, true, true, false, false, false, true, true,
    false, true, true, false, false, true, true, false, true, true, true, false, false, true, true,
    false, false, false, true, true, false, false, false, true, false, false, false, false, true,
    true, false, false, false, false, true, true, true, false, false, false, false, true, true,
    true, true, false, false, false, false, true, true, true, false, false, false, true, true,
    false, false, false, false, true, false, false, false, true, false, false, false, true, false,
    false, false, true, true, true, false, false, true, true, false, true, true, false, true, true,
    true, false, false, true, true, true, false, false, false, false, true, false, false, false,
    false, true, true, false, true, true, true, false, true, true, true, false, false, false, true,
    false, false, false, false, true, true, true, false, true, true, true, true, false, false,
    true, true, false, false, false, false, true, true, true, true, false, false, true, true, true,
    false, false, false, true, false, true, false, true, true, true, true, false, false, true,
    true, true, true, false, true, false, true, true, true, true, false, false, true, false, false,
    false, false, true, true, false, false, false, false, true, true, false, false, false, true,
    true, false, true, true, true, false, false, true, true, true, false, false, false, false,
    true, true, true, true, false, false, false, false, true, true, false, false, false, false,
    true, false, false, true, false, true, true, true, true, false, false, false, true, true,
    false, false, true, true, false, false, false, true, true, true, true, false, true, false,
    false, false, true, false, false, false, true, true, true, false, true, true, true, true,
    false, false, true, true, true, false, false, false, false, true, true, true, true, false,
    true, false, true, true, false, true, true, true, false, false, false, false, true, true,
    false, false, true, false, true, true, true, true, false, false, false, true, true, false,
    false, false, false, true, false, false, false, true, true, true, false, true, true, true,
    false, false, true, false, false, false, true, true, true, false, false, false, false, true,
    true, false, false, false, true, true, false, false, false, true, true, true, false, true,
    true, true, true, false, false, false, true, true, true, true, false, false, false, true, true,
    true, true, false, false, false, true, true, true, false, false, false, false, true, true,
    false, false, false, false, true, true, false, false, false, false, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, true, false, true, true,
    false, true, true, false, false, true, true, true, true, false, true, true, true, true, false,
    true, false, false, false, false, true, true, false, false, true, false, false, true, true,
    false, true, true, false, true, true, true, true, false, false, true, true, true, true, false,
    false, true, true, true, false, false, true, true, true, true, false, false, true, true, false,
    false, false, true, true, false, false, false, false, true, true, true, true, false, false,
    false, false, true, false, true, true, true, false, false, false, false, true, false, false,
    true, false, false, false, true, false, false, false, true, true, false, true, false, false,
    false, true, true, true, true, false, false, true, true, true, false, false, false, true, true,
    true, true, false, true, true, true, false, false, false, false, true, true, true, false,
    false, false, true, true, true, false, false, false, true, true, true, false, true, true, true,
    false, false, false, false, true, true, false, false, true, true, true, true, false, true,
    false, true, true, true, false, false, true, true, true, true, false, false, true, true, true,
    false, false, true, true, true, false, true, false, false, false, true, true, true, false,
    false, false, false, true, false, false, false, true, true, true, true, false, false, false,
    true, false, false, false, false, true, true, false, true, true, true, false, false, false,
    true, true, true, false, true, true, true, false, false, true, false, false, true, false,
    false, true, true, true, true, false, false, true, true, true, false, false, false, true,
    false, false, true, false, false, true, true, true, true, false, false, false, true, true,
    false, false, true, true, false, false, false, false, true, true, false, true, true, true,
    true, false, true, true, false, true, true, false, true, false, true, true, false, true, false,
    false, true, true, true, true, false, true, true, false, false, false, true, true, true, true,
    false, false, true, false, false, false, true, true, false, false, false, false, true, true,
    false, false, true, false, false, false, false, true, false, false, true, false, true, true,
    true, false, false, true, true, true, false, false, true, true, false, false, false, true,
    true, true, true, false, false, false, false, true, true, true, true, false, false, false,
    false, true, true, true, true, false, false, false, false, true, true, false, false, false,
    false, true, false, false, false, true, true, true, false, false, false, true, false, false,
    true, true, false, true, false, false, true, true, true, true, false, false, true, false, true,
    true, false, true, true, true, true, false, true, true, true, true, false, false, true, true,
    true, false, false, true, false, false, false, true, true, true, true, false, false, false,
    false, true, true, true, true, false, true, true, true, true, false, true, true, false, false,
    false, false, true, true, true, true, false, true, true, true, true, false, false, false, true,
    true, false, false, true, true, false, false, false, false, true, false, false, true, true,
    true, true, false, false, false, true, true, true, true, false, true, true, true, true, false,
    false, true, true, true, true, false, true, true, false, true, false, false, false, false,
    true, true, true, true, false, false, false, true, false, false, true, true, false, false,
    false, false, true, true, true, true, false, false, false, true, true, true, true, false,
    false, false, false, true, false, false, false, true, true, false, true, true, true, true,
    false, false, false, false, true, true, false, false, false, true, false, false, false, false,
    true, true, true, false, false, false, true, true, false, false, true, true, true, true, false,
    false, false, false, true, true, false, false, false, true, false, false, true, true, false,
    false, false, true,
];
